"use client";
import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Checkbox } from '@/components/ui/checkbox';
import { Switch } from '@/components/ui/switch';
import { Textarea } from '@/components/ui/textarea';
import { Progress } from '@/components/ui/progress';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { RefreshCw, KeyRound, FileText, History, Loader2 } from 'lucide-react';
import { toast } from 'sonner';
import type { Company } from '@/lib/types';
import type { Job } from '@/lib/jobs';
import type { DocumentData } from '@/lib/documents';
import type { diagnostics } from '@/lib/maintenance';
import type { aiStatus } from '@/lib/ai-settings';

async function api<T>(path:string,method='GET',body?:unknown):Promise<T> {
  const response=await fetch(path,{method,...(body instanceof FormData ? {body} : {headers:{'content-type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})})});
  const data=await response.json(); if (!response.ok) throw new Error(data.error || 'Request failed'); return data;
}
const fail=(e:unknown)=>toast.error(e instanceof Error ? e.message : 'Request failed');
const date=(offset=0)=>new Date(Date.now()-offset*86400000).toISOString().slice(0,10);
type Diagnostics=Awaited<ReturnType<typeof diagnostics>>;
type AIStatus=Awaited<ReturnType<typeof aiStatus>>;

export function AISettings({onSaved}:{onSaved:()=>Promise<void>}) {
  const [status,setStatus]=useState<AIStatus|null>(null),[key,setKey]=useState(''),[auto,setAuto]=useState(false),[limit,setLimit]=useState(30),[busy,setBusy]=useState(false),[error,setError]=useState('');
  useEffect(()=>{api<AIStatus>('/api/ai/config').then(s=>{setStatus(s);setAuto(s.autoEnrich);setLimit(s.dailyLimit)}).catch(e=>setError(e.message));},[]);
  async function save(e:FormEvent){e.preventDefault();setBusy(true);setError('');try {setStatus(await api<AIStatus>('/api/ai/config','POST',{...(key?{apiKey:key}:{}),autoEnrich:auto,dailyLimit:limit}));setKey('');await onSaved();toast.success('Private AI settings saved.');}catch(e){setError(e instanceof Error?e.message:'Could not save key');}finally{setBusy(false)}}
  return <section className="panel settings-panel"><h3><KeyRound size={18}/>Private AI connection</h3><p>{status?.configured?`Key ending ${status.last4} · ${status.model}`:'Add your OpenAI API key here to enable multilingual analysis, translation, semantic retrieval and PDF OCR.'}</p><form onSubmit={save} className="data-form"><label>API key<Input type="password" autoComplete="new-password" value={key} onChange={e=>setKey(e.target.value)} placeholder={status?.configured?'Enter a replacement key':'sk-…'} disabled={busy || !status?.secureStorage}/></label><p className="panel-footnote">Stored encrypted on the server. The key is never returned to the browser. Validation checks model access; billing and usage limits still apply.</p><div className="setting-row"><label htmlFor="auto-ai">Automatically enrich new articles</label><Switch id="auto-ai" checked={auto} onCheckedChange={setAuto}/></div><label>Daily background AI attempt limit<Input type="number" min={1} max={300} required value={limit} onChange={e=>setLimit(Number(e.target.value))}/></label><p className="panel-footnote">One attempt can make an analysis call and an embedding call, or process one OCR page. This is a call limit, not a currency budget. Asking questions and manual enrichment are additional usage. OCR sends uploaded pages to OpenAI only when you enable it.</p>{error&&<p role="alert" className="source-error">{error}</p>}<div className="data-actions"><Button type="submit" disabled={busy || !status || (!status.configured&&!key)}>{busy?<Loader2 className="spin" size={16}/>:<KeyRound size={16}/>}Save & validate</Button>{status?.origin==='private-settings'&&<Button type="button" variant="outline" disabled={busy} onClick={async()=>{setBusy(true);try{setStatus(await api<AIStatus>('/api/ai/config','DELETE'));await onSaved();toast.success('Stored key removed');}catch(e){fail(e)}finally{setBusy(false)}}}>Remove key</Button>}</div></form></section>;
}

export function DataWorkspace({companies,onChanged}:{companies:Company[];onChanged:()=>Promise<void>}) {
  const real=companies.filter(c=>!c.demo),[data,setData]=useState<Diagnostics|null>(null),[docs,setDocs]=useState<Job<DocumentData>[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const [from,setFrom]=useState(date(44)),[to,setTo]=useState(date()),[selected,setSelected]=useState<string[]>(real.map(c=>c.id));
  const [documentCompany,setDocumentCompany]=useState(real[0]?.id || ''),[language,setLanguage]=useState('en');
  const reload=useCallback(async()=>{try{const [d,p]=await Promise.all([api<Diagnostics>('/api/diagnostics'),api<{jobs:Job<DocumentData>[]}>('/api/documents')]);setData(d);setDocs(p.jobs);setError('')}catch(e){setError(e instanceof Error?e.message:'Could not load import status')}},[]);
  useEffect(()=>{void reload();const id=setInterval(()=>void reload(),15000);return()=>clearInterval(id)},[reload]);
  async function run(){setBusy(true);try{const result=await api<{pending:boolean;errors:string[]}>('/api/maintenance','POST',{});await reload();await onChanged();if(result.errors?.length)toast.error(result.errors.join('; '));else toast.success(result.pending?'Batch saved. More work remains queued.':'Maintenance is up to date.')}catch(e){fail(e)}finally{setBusy(false)}}
  async function backfill(e:FormEvent){e.preventDefault();setBusy(true);try{await api('/api/backfill','POST',{companyIds:selected,from,to});await reload();toast.success('Historical jobs queued. Progress is saved after each step.')}catch(e){fail(e)}finally{setBusy(false)}}
  async function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,body=new FormData(form);body.set('companyId',documentCompany);body.set('language',language);body.set('ocr',body.has('ocr')?'true':'false');setBusy(true);try{await api('/api/documents','POST',body);form.reset();await reload();toast.success('PDF stored privately and queued for extraction.')}catch(e){fail(e)}finally{setBusy(false)}}
  async function action(id:string,action:string){setBusy(true);try{await api('/api/backfill','PATCH',{id,action});await reload()}catch(e){fail(e)}finally{setBusy(false)}}
  return <div className="data-workspace"><div className="data-actions"><Button onClick={()=>void run()} disabled={busy}>{busy?<Loader2 className="spin" size={16}/>:<RefreshCw size={16}/>}Process next batch</Button><Button variant="outline" disabled={busy} onClick={()=>void reload()}>Refresh status</Button><span className="muted">Progress persists when you close this page.</span></div>{error&&<p role="alert" className="source-error">{error}</p>}
    <div className="data-metrics">{[['Collected in latest snapshot',data?.collected],['Imported into cloud database',data?.imported],['Pending in current snapshot',data?.pendingRecords],['Sources needing attention',data?.failedSources]].map(([label,value])=><section className="panel" key={String(label)}><span>{label}</span><strong>{value===null||value===undefined?'—':String(value)}</strong></section>)}</div>
    <p className="panel-footnote">{data?.scope || 'Loading verified counts…'} {data?.pendingSnapshots?`${data.pendingSnapshots} snapshots remain queued.`:''}</p>
    <div className="panel data-status"><strong>Background worker</strong><p>{data?.maintenance?.at?`Last heartbeat: ${new Date(data.maintenance.at).toLocaleString()}.`:'No maintenance heartbeat has been recorded yet.'} {data?.schedule.error || ''}</p>{data?.historicalRetryAt&&<p>Historical search retry time: {new Date(data.historicalRetryAt).toLocaleString()}. Unfinished dates remain queued; publisher pages already found can still be imported.</p>}{data?.maintenance?.errors?.length>0&&<p role="alert" className="source-error">{data?.maintenance?.errors.join('; ')}</p>}</div>
    <Tabs defaultValue="history"><TabsList><TabsTrigger value="history"><History size={16}/>Historical backfill</TabsTrigger><TabsTrigger value="documents"><FileText size={16}/>PDF & OCR</TabsTrigger><TabsTrigger value="coverage">Coverage gaps</TabsTrigger></TabsList>
    <TabsContent value="history"><section className="panel data-card"><h3>Recover past reporting</h3><p>Search the public GDELT index, then verify accessible articles from enabled publishers. Publication dates and company matches are checked before storage. Search coverage is incomplete, especially for regional and small-company reporting.</p><form onSubmit={backfill} className="data-form"><div className="data-date-row"><label>From<Input type="date" required min={date(89)} max={to} value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Through<Input type="date" required min={from} max={date()} value={to} onChange={e=>setTo(e.target.value)}/></label><Button type="button" variant="outline" onClick={()=>{setFrom(date(44));setTo(date())}}>Last 45 days</Button></div><div className="data-actions"><Button variant="ghost" type="button" onClick={()=>setSelected(real.map(c=>c.id))}>Select all</Button><Button variant="ghost" type="button" onClick={()=>setSelected([])}>Clear</Button><span>{selected.length} companies</span></div><div className="company-checks">{real.map(c=><label key={c.id}><Checkbox checked={selected.includes(c.id)} onCheckedChange={v=>setSelected(s=>v?[...s,c.id]:s.filter(id=>id!==c.id))}/>{c.name}</label>)}</div><Button type="submit" disabled={busy||!selected.length}>Queue historical search</Button></form></section>
    <Accordion type="multiple" className="panel data-card">{(data?.backfill || []).map(j=><AccordionItem key={j.id} value={j.id}><AccordionTrigger><div className="job-heading"><strong>{real.find(c=>c.id===j.companyId)?.name}</strong><span>{j.data.from} → {j.data.to} · {j.status} · {j.data.imported} imported</span></div></AccordionTrigger><AccordionContent><Progress value={Math.min(100,100*(j.data.windows-(j.data.pendingCandidates>0?1:0))/j.data.totalWindows)}/><p>{j.data.windows}/{j.data.totalWindows} search windows checked · {j.data.collected} collected · {j.data.pendingCandidates} pending · {j.data.imported} imported · {j.data.duplicates} already stored · {j.data.failed} failed · {j.data.unknownDate} unknown dates · {j.data.outsideRange} outside dates · {j.data.unmatched} unrelated</p><div className="data-actions"><Button size="sm" variant="outline" disabled={busy} onClick={()=>void action(j.id,['queued','running'].includes(j.status)?'pause':'resume')}>{['queued','running'].includes(j.status)?'Pause':'Resume'}</Button>{['partial','failed','completed'].includes(j.status)&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>void action(j.id,'retry')}>Recheck date range</Button>}</div>{j.error&&<p className="source-error">{j.error}</p>}{j.data.gaps.length>0&&<ul className="coverage-gaps">{j.data.gaps.map((g,i)=><li key={i}>{g}</li>)}</ul>}</AccordionContent></AccordionItem>)}</Accordion>{data&&!data.backfill.length&&<p className="muted">No historical jobs yet. Choose dates and companies above.</p>}</TabsContent>
    <TabsContent value="documents"><section className="panel data-card"><h3>Company announcements & regional documents</h3><p>Upload a PDF up to 4 MB and 20 pages. Text layers are extracted locally on the server. Scanned pages can use OpenAI vision OCR; review its transcription before it enters search.</p><form className="data-form" onSubmit={upload}><label>Company<Select value={documentCompany} onValueChange={setDocumentCompany}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{real.map(c=><SelectItem key={c.id} value={c.id}>{c.name}</SelectItem>)}</SelectContent></Select></label><label>PDF<Input name="file" type="file" accept="application/pdf,.pdf" required/></label><div className="data-date-row"><label>Publisher URL (optional)<Input name="sourceUrl" type="url" placeholder="https://…"/></label><label>Publication date (optional)<Input name="publishedAt" type="date" max={date()}/></label><label>Language<Select value={language} onValueChange={setLanguage}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{Object.entries({en:'English',hi:'Hindi',ta:'Tamil',kn:'Kannada',ml:'Malayalam',te:'Telugu'}).map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select></label></div><label className="data-actions"><Checkbox name="ocr"/>Use paid vision OCR for scanned pages (requires a configured API key)</label><Button type="submit" disabled={busy}>Upload & queue extraction</Button></form></section>
    <Accordion type="multiple" className="panel data-card">{docs.map(j=><AccordionItem key={j.id} value={j.id}><AccordionTrigger>{j.data.title} · {j.data.cursor}/{j.data.pageCount} pages · {j.status}</AccordionTrigger><AccordionContent><a href={`/api/documents/${j.id}/file`}>Download original PDF</a>{j.data.sourceUrl&&<p><a href={j.data.sourceUrl} target="_blank" rel="noreferrer">Publisher reference</a></p>}{j.error&&<p className="source-error">{j.error}</p>}{['failed','waiting-key','review'].includes(j.status)&&j.data.pages.some(p=>p.method==='unreadable')||j.status==='failed'||j.status==='waiting-key'?<Button variant="outline" disabled={busy} onClick={async()=>{try{await api('/api/documents/retry','POST',{id:j.id,ocr:true});await reload()}catch(e){fail(e)}}}>Retry with OCR enabled</Button>:null}{j.data.pages.map(p=><PageReview key={p.number} job={j} page={p} reload={reload}/>)}</AccordionContent></AccordionItem>)}</Accordion></TabsContent>
    <TabsContent value="coverage"><section className="panel data-card"><h3>Stored coverage by company</h3><p>A zero count means no verified matching article has been imported. It is not a positive or negative assessment of the company.</p><Table><TableHeader><TableRow><TableHead>Company</TableHead><TableHead>Stored</TableHead><TableHead>AI enriched</TableHead><TableHead>Latest publication</TableHead></TableRow></TableHeader><TableBody>{data?.companies.map(c=><TableRow key={String(c.id)}><TableCell>{String(c.name)}</TableCell><TableCell>{Number(c.stored)}</TableCell><TableCell>{Number(c.enriched)}</TableCell><TableCell>{c.latest?String(c.latest).slice(0,10):'No dated articles stored'}</TableCell></TableRow>)}</TableBody></Table></section><Accordion type="multiple" className="panel data-card">{data?.sources.map(s=><AccordionItem key={s.id} value={s.id}><AccordionTrigger>{s.name} · {s.category}</AccordionTrigger><AccordionContent><p>{s.error}</p><p>{s.action}</p></AccordionContent></AccordionItem>)}</Accordion></TabsContent></Tabs>
  </div>;
}
function PageReview({job,page,reload}:{job:Job<DocumentData>;page:DocumentData['pages'][number];reload:()=>Promise<void>}) {
  const [text,setText]=useState(page.text),[busy,setBusy]=useState(false);
  return <section className="document-page"><strong>Page {page.number} · {page.method} · {page.articleId?'Imported':page.reviewed?'Reviewed':'Needs review'}</strong><p>{page.note}</p><Textarea aria-label={`Page ${page.number} transcription`} value={text} onChange={e=>setText(e.target.value)} rows={6} readOnly={!!page.articleId}/>{!page.articleId&&text&&<Button disabled={busy} variant="outline" onClick={async()=>{setBusy(true);try{const r=await api<{imported:boolean}>('/api/documents/review','POST',{id:job.id,page:page.number,text});await reload();toast.success(r.imported?'Reviewed page imported':'Review saved; no company match on this page')}catch(e){fail(e)}finally{setBusy(false)}}}>Approve transcription</Button>}</section>;
}
