"use client";
import { useMemo, useState } from 'react';
import { ArrowUpRight, Check, ChevronLeft, ChevronRight, CircleHelp, Clock3, Globe2, Languages, RefreshCw, Rss, Search } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Switch } from '@/components/ui/switch';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Empty, EmptyDescription, EmptyHeader, EmptyTitle } from '@/components/ui/empty';
import { LANGUAGES, sourcePublisher, sourceZone } from '@/lib/catalog';
import type { Source } from '@/lib/types';
const languageNames: Record<string, string> = LANGUAGES;
const zones = ['All regions', 'National', 'North', 'South', 'East', 'West', 'Central', 'North East', 'Global'];
const date = (value: string | null) => value ? new Intl.DateTimeFormat('en-IN', { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit', timeZone: 'Asia/Kolkata' }).format(new Date(value)) : 'Awaiting first check';
function Filter({ value, label, values, onChange }: { value: string; label: string; values: { value: string; label: string }[]; onChange: (value: string) => void }) {
 return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue /></SelectTrigger><SelectContent>{values.map(v => <SelectItem value={v.value} key={v.value}>{v.label}</SelectItem>)}</SelectContent></Select>;
}
export function SourceDirectory({ sources, busy, check, toggle }: { sources: Source[]; busy: boolean; check: (ids: string[]) => void; toggle: (ids: string[], enabled: boolean) => Promise<void> }) {
 const [search, setSearch] = useState(''), [zone, setZone] = useState('All regions'), [language, setLanguage] = useState('all'), [health, setHealth] = useState('all'), [region, setRegion] = useState('all'), [page, setPage] = useState(0), [saving, setSaving] = useState(false);
 const filtered = useMemo(() => sources.filter(s => (zone === 'All regions' || sourceZone(s.region) === zone) && (region === 'all' || s.region === region) && (language === 'all' || s.language === language) && (health === 'all' || health === 'paused' ? health === 'all' || !s.enabled : health === 'enabled' ? s.enabled : s.status === health) && `${s.name} ${s.region} ${sourcePublisher(s)} ${s.url}`.toLowerCase().includes(search.toLowerCase())), [sources, zone, region, language, health, search]);
 const pages = Math.max(1, Math.ceil(filtered.length / 12)), current = Math.min(page, pages - 1), visible = filtered.slice(current * 12, current * 12 + 12);
 const reset = () => { setSearch(''); setZone('All regions'); setRegion('all'); setLanguage('all'); setHealth('all'); setPage(0); };
 const change = (setter: (v: string) => void) => (v: string) => { setter(v); setPage(0); };
 const update = async (ids: string[], enabled: boolean) => { setSaving(true); try { await toggle(ids, enabled); } finally { setSaving(false); } };
 const regionValues = [...new Set(sources.filter(s => zone === 'All regions' || sourceZone(s.region) === zone).map(s => s.region))].sort();
 return <div className="source-directory">
  <div className="coverage-counters"><div><Rss size={19}/><strong>{sources.filter(s => s.region !== 'Global').length}</strong><span>Indian sources</span></div><div><Globe2 size={19}/><strong>{sources.filter(s => s.region === 'Global').length}</strong><span>Global sources</span></div><div><Languages size={19}/><strong>{new Set(sources.map(s => s.language)).size}</strong><span>Source languages</span></div><div><Check size={19}/><strong>{sources.filter(s => s.status === 'healthy').length}<small> / {sources.length}</small></strong><span>Last check succeeded</span></div></div>
  <div className="region-filters" aria-label="Filter sources by Indian region">{zones.map(z => <button key={z} aria-pressed={zone === z} onClick={() => { setZone(z); setRegion('all'); setPage(0); }}>{z}<span>{sources.filter(s => z === 'All regions' || sourceZone(s.region) === z).length}</span></button>)}</div>
  <section className="source-table-panel"><div className="directory-tools"><div className="coverage-search"><Search size={16}/><Input aria-label="Search sources" value={search} onChange={e => change(setSearch)(e.target.value)} placeholder="Search publication or place…"/></div><Filter value={region} onChange={change(setRegion)} label="State or coverage area" values={[{value:'all',label:'All states / areas'},...regionValues.map(v=>({value:v,label:v}))]}/><Filter value={language} onChange={change(setLanguage)} label="Source language filter" values={[{value:'all',label:'All languages'},...Object.entries(LANGUAGES).filter(([code])=>sources.some(s=>s.language===code)).map(([value,label])=>({value,label}))]}/><Filter value={health} onChange={change(setHealth)} label="Source health filter" values={[{value:'all',label:'Any status'},{value:'enabled',label:'Monitoring on'},{value:'paused',label:'Paused'},{value:'healthy',label:'Fetch succeeded'},{value:'error',label:'Needs attention'},{value:'unfetched',label:'Not checked'}]}/></div>
  <div className="directory-results"><span><strong>{filtered.length}</strong> matching sources · {new Set(filtered.map(sourcePublisher)).size} publications / products</span><div><Button variant="ghost" size="sm" onClick={reset}>Clear filters</Button><Button variant="outline" size="sm" disabled={busy||saving||!filtered.length} onClick={()=>void update(filtered.map(s=>s.id),!filtered.every(s=>s.enabled))}>{filtered.length && filtered.every(s=>s.enabled)?'Pause':'Enable'} filtered</Button><Button size="sm" disabled={busy||!filtered.some(s=>s.enabled)} onClick={()=>check(filtered.filter(s=>s.enabled).map(s=>s.id))}><RefreshCw size={14}/>Check filtered</Button></div></div>
  {visible.length ? <Table><TableHeader><TableRow><TableHead>Publication / source</TableHead><TableHead>Coverage</TableHead><TableHead>Language</TableHead><TableHead>Last check · IST</TableHead><TableHead>Monitor</TableHead><TableHead><span className="sr-only">Actions</span></TableHead></TableRow></TableHeader><TableBody>{visible.map(s=><TableRow key={s.id} className={!s.enabled?'source-paused':''}><TableCell><a className="directory-source" href={s.url} target="_blank" rel="noreferrer">{s.name}<ArrowUpRight size={13}/></a><span className="source-host">{new URL(s.url).hostname} · {s.kind==='discovery'?'Feed discovery':s.kind==='rss'?'RSS / Atom':'Single article'}</span></TableCell><TableCell><span className="event-tag">{s.region}</span><span className="source-host">{sourceZone(s.region)}</span></TableCell><TableCell>{languageNames[s.language]||s.language}</TableCell><TableCell><span className={`status-label status-${s.status}`}>{s.status==='healthy'?<Check size={13}/>:s.status==='error'?<CircleHelp size={13}/>:<Clock3 size={13}/>} {s.status==='healthy'?'Succeeded':s.status==='error'?'Needs attention':'Not checked'}</span><span className="source-host">{date(s.lastFetchedAt)}</span>{s.error&&<details className="source-error-details"><summary>See reason</summary><p>{s.error}</p></details>}</TableCell><TableCell><Switch checked={s.enabled} aria-label={`Monitor ${s.name}`} disabled={busy||saving} onCheckedChange={enabled=>void update([s.id],enabled)}/></TableCell><TableCell><Button variant="ghost" size="icon" aria-label={`Check ${s.name}`} disabled={!s.enabled||busy} onClick={()=>check([s.id])}><RefreshCw size={15}/></Button></TableCell></TableRow>)}</TableBody></Table> : <Empty><EmptyHeader><EmptyTitle>No matching sources</EmptyTitle><EmptyDescription>Try a different region, language or publication.</EmptyDescription></EmptyHeader><Button variant="outline" onClick={reset}>Reset filters</Button></Empty>}
  <div className="directory-pagination"><span>{filtered.length?current*12+1:0}–{Math.min((current+1)*12,filtered.length)} of {filtered.length}</span><div><Button size="sm" variant="outline" disabled={current===0} onClick={()=>setPage(current-1)}><ChevronLeft size={15}/>Previous</Button><span>Page {current+1} of {pages}</span><Button size="sm" variant="outline" disabled={current>=pages-1} onClick={()=>setPage(current+1)}>Next<ChevronRight size={15}/></Button></div></div></section>
  <p className="panel-footnote">Multiple feeds from one publisher do not count as independent confirmation. Availability is measured on collection; listed feeds can be restricted or temporarily unavailable. Feed discovery checks a publisher’s advertised feed links. If none are available, import an accessible article or excerpt manually.</p>
 </div>;
}
